import ast
import json

# names.txt 파일 읽기
with open('names.txt', 'r', encoding='utf-8') as f:
    content = f.read()

# Python 리스트 파싱
tech_list = ast.literal_eval(content)

# 각 기술에 대한 한줄 소개 딕셔너리
tech_descriptions = {
    # DevOps & CI/CD
    "GitHub Actions": "GitHub에서 제공하는 CI/CD 워크플로우 자동화 도구",
    "Travis CI": "클라우드 기반 지속적 통합(CI) 서비스",
    "CircleCI": "빠르고 유연한 CI/CD 파이프라인 플랫폼",
    "Jenkins": "오픈소스 자동화 서버로 CI/CD 구축에 널리 사용",
    "GitLab CI": "GitLab 통합 CI/CD 파이프라인 도구",
    "Docker": "컨테이너 기반 가상화 플랫폼",
    "Docker Compose": "여러 Docker 컨테이너를 정의하고 실행하는 도구",
    "Kubernetes": "컨테이너 오케스트레이션 플랫폼",
    "Terraform": "코드형 인프라(IaC) 도구",

    # Version Control
    "Git": "분산 버전 관리 시스템",
    "GitHub": "Git 기반 코드 호스팅 및 협업 플랫폼",
    "GitLab": "DevOps 라이프사이클 전체를 지원하는 Git 저장소 관리 도구",
    "Bitbucket": "Atlassian의 Git 저장소 호스팅 서비스",
    "SVN (Subversion)": "중앙집중식 버전 관리 시스템",

    # Programming Languages
    "JavaScript": "웹 개발의 핵심 프로그래밍 언어",
    "Python": "다목적 고급 프로그래밍 언어",
    "Java": "객체지향 프로그래밍 언어로 JVM에서 실행",
    "TypeScript": "JavaScript의 상위 집합으로 정적 타입을 추가한 언어",
    "C#": "Microsoft가 개발한 객체지향 프로그래밍 언어",
    "Ruby": "간결하고 읽기 쉬운 동적 프로그래밍 언어",
    "PHP": "서버 사이드 스크립팅 언어",
    "Golang": "Google이 개발한 컴파일 언어",
    "Swift": "Apple 플랫폼 개발을 위한 프로그래밍 언어",
    "Kotlin": "JVM에서 실행되는 현대적인 프로그래밍 언어",
    "Rust": "안전성과 성능을 중시하는 시스템 프로그래밍 언어",
    "Scala": "함수형 및 객체지향 프로그래밍을 결합한 JVM 언어",
    "C lang": "시스템 프로그래밍을 위한 저수준 언어",
    "C++": "C의 확장으로 객체지향을 지원하는 언어",
    "Objective-C": "Apple 플랫폼의 레거시 프로그래밍 언어",
    "R Language": "통계 분석 및 데이터 시각화 언어",
    "Perl": "텍스트 처리에 강한 스크립팅 언어",
    "Elixir": "Erlang VM에서 실행되는 함수형 언어",
    "Dart": "Flutter 프레임워크를 위한 언어",
    "Groovy": "JVM에서 실행되는 동적 언어",
    "Lua": "경량 임베디드 스크립팅 언어",
    "CoffeeScript": "JavaScript로 컴파일되는 언어",
    "Haskell": "순수 함수형 프로그래밍 언어",
    "Erlang": "동시성과 분산 처리에 강한 함수형 언어",
    "Clojure": "JVM에서 실행되는 Lisp 계열 함수형 언어",
    "F#": ".NET 플랫폼의 함수형 프로그래밍 언어",
    "Julia": "고성능 과학 컴퓨팅 언어",
    "Elm": "웹 프론트엔드를 위한 함수형 언어",
    "Crystal": "Ruby 문법에 정적 타입을 추가한 컴파일 언어",
    "Hack": "Facebook이 개발한 PHP 대체 언어",
    "D": "C++의 대안으로 설계된 시스템 프로그래밍 언어",
    "Assembly Language": "기계어에 가까운 저수준 프로그래밍 언어",

    # Frontend Frameworks
    "React": "UI 구축을 위한 JavaScript 라이브러리",
    "Vue.js": "진보적인 JavaScript 프레임워크",
    "Angular": "TypeScript 기반 웹 애플리케이션 프레임워크",
    "AngularJS": "Angular의 구버전 JavaScript 프레임워크",
    "Next.js": "React 기반 서버 사이드 렌더링 프레임워크",
    "Nuxt.js": "Vue.js 기반 서버 사이드 렌더링 프레임워크",
    "Svelte": "컴파일 타임에 최적화하는 프론트엔드 프레임워크",
    "Gatsby": "React 기반 정적 사이트 생성기",
    "Ember.js": "생산성 높은 JavaScript 프레임워크",
    "Preact": "React의 경량화 대안",

    # Backend Frameworks
    "Django": "Python 기반 고수준 웹 프레임워크",
    "Flask": "Python 마이크로 웹 프레임워크",
    "ExpressJS": "Node.js 웹 애플리케이션 프레임워크",
    "Rails": "Ruby on Rails, Ruby 기반 웹 프레임워크",
    "Spring Boot": "Java 기반 마이크로서비스 프레임워크",
    "Laravel": "PHP 웹 애플리케이션 프레임워크",
    "ASP.NET": "Microsoft의 웹 애플리케이션 프레임워크",
    "ASP.NET Core": "크로스 플랫폼 지원하는 ASP.NET의 현대적 버전",
    "NestJS": "TypeScript 기반 Node.js 프레임워크",
    "FastAPI": "Python 비동기 웹 프레임워크",
    "Symfony": "PHP 웹 애플리케이션 프레임워크",
    "CodeIgniter": "경량 PHP 프레임워크",
    "CakePHP": "PHP MVC 프레임워크",
    "Yii": "고성능 PHP 프레임워크",
    "Lumen": "Laravel의 마이크로 프레임워크",
    "Phalcon": "C 확장으로 작성된 PHP 프레임워크",
    "AdonisJS": "Node.js MVC 프레임워크",
    "Koa": "Express 팀이 만든 차세대 Node.js 프레임워크",
    "hapi": "Node.js 웹 프레임워크",
    "Sails.js": "Node.js MVC 프레임워크",
    "Phoenix Framework": "Elixir 웹 프레임워크",
    "Gin Gonic": "Go 언어 웹 프레임워크",
    "Echo": "Go 언어 고성능 웹 프레임워크",
    "Fastify": "빠른 Node.js 웹 프레임워크",
    "LoopBack": "Node.js API 프레임워크",
    "Grails": "Groovy 기반 웹 프레임워크",
    "Play": "Scala/Java 웹 프레임워크",
    "Ktor": "Kotlin 비동기 웹 프레임워크",
    "Quarkus": "Kubernetes 최적화 Java 프레임워크",
    "Micronaut Framework": "JVM 마이크로서비스 프레임워크",
    "Tornado": "Python 비동기 웹 프레임워크",
    "Sinatra": "Ruby 마이크로 웹 프레임워크",
    "Strapi": "Headless CMS 및 Node.js 프레임워크",
    "FeathersJS": "실시간 애플리케이션을 위한 Node.js 프레임워크",
    "Dropwizard": "Java RESTful 웹 서비스 프레임워크",
    "Vert.x": "JVM 기반 반응형 애플리케이션 툴킷",

    # Databases
    "MySQL": "오픈소스 관계형 데이터베이스",
    "PostgreSQL": "고급 오픈소스 관계형 데이터베이스",
    "MongoDB": "문서 지향 NoSQL 데이터베이스",
    "Redis": "인메모리 키-값 데이터 저장소",
    "SQLite": "경량 임베디드 관계형 데이터베이스",
    "Microsoft SQL Server": "Microsoft의 관계형 데이터베이스 관리 시스템",
    "MariaDB": "MySQL 포크 오픈소스 데이터베이스",
    "Oracle": "엔터프라이즈급 관계형 데이터베이스",
    "Cassandra": "분산형 NoSQL 데이터베이스",
    "Elasticsearch": "분산 검색 및 분석 엔진",
    "Amazon DynamoDB": "AWS의 완전 관리형 NoSQL 데이터베이스",
    "Neo4j": "그래프 데이터베이스",
    "Amazon RDS": "AWS 관리형 관계형 데이터베이스 서비스",
    "CouchDB": "문서 지향 NoSQL 데이터베이스",
    "RethinkDB": "실시간 애플리케이션을 위한 NoSQL 데이터베이스",
    "InfluxDB": "시계열 데이터베이스",
    "TimescaleDB": "PostgreSQL 기반 시계열 데이터베이스",
    "CockroachDB": "분산 SQL 데이터베이스",
    "Amazon Aurora": "MySQL/PostgreSQL 호환 클라우드 데이터베이스",
    "Azure Cosmos DB": "Azure의 전역 분산 데이터베이스",
    "Amazon Redshift": "AWS 데이터 웨어하우스",
    "Snowflake": "클라우드 데이터 웨어하우스",
    "Couchbase": "분산 NoSQL 클라우드 데이터베이스",
    "ArangoDB": "다중 모델 NoSQL 데이터베이스",
    "HBase": "Hadoop 기반 분산 NoSQL 데이터베이스",
    "Clickhouse": "컬럼 지향 분석용 데이터베이스",
    "H2 Database": "Java로 작성된 임베디드 데이터베이스",
    "HSQLDB": "Java 기반 관계형 데이터베이스",
    "Realm": "모바일 데이터베이스",
    "Amazon Athena": "서버리스 대화형 쿼리 서비스",
    "Amazon Kinesis": "실시간 스트리밍 데이터 처리",
    "Presto": "분산 SQL 쿼리 엔진",
    "Druid": "실시간 분석 데이터베이스",
    "MongoDB Atlas": "MongoDB 클라우드 데이터베이스",
    "Cloud DB for Mysql": "클라우드 MySQL 관리 서비스",
    "Cloud Firestore": "Firebase 실시간 NoSQL 데이터베이스",
    "Amazon Elasticsearch Service": "AWS 관리형 Elasticsearch",
    "Azure SQL Database": "Azure 관리형 SQL 데이터베이스",
    "Amazon RDS for PostgreSQL": "AWS 관리형 PostgreSQL",
    "Google Cloud SQL": "Google Cloud 관리형 관계형 데이터베이스",
    "Amazon SageMaker": "AWS 머신러닝 플랫폼 및 데이터 관리",
    "Amazon EBS": "AWS 블록 스토리지",
    "Amazon ElastiCache": "AWS 인메모리 캐싱 서비스",
    "pgvector": "PostgreSQL 벡터 유사도 검색 확장",

    # Cloud Platforms
    "Amazon Web Services (AWS)": "Amazon의 클라우드 컴퓨팅 플랫폼",
    "Microsoft Azure": "Microsoft의 클라우드 컴퓨팅 플랫폼",
    "Google Cloud Platform": "Google의 클라우드 컴퓨팅 서비스",
    "Heroku": "클라우드 애플리케이션 플랫폼",
    "DigitalOcean": "개발자 친화적 클라우드 인프라",
    "Amazon EC2": "AWS 가상 서버 인스턴스",
    "Amazon S3": "AWS 객체 스토리지 서비스",
    "AWS Lambda": "서버리스 컴퓨팅 서비스",
    "Amazon EC2 Container Service": "AWS 컨테이너 오케스트레이션",
    "AWS Elastic Beanstalk": "애플리케이션 배포 및 관리 서비스",
    "Amazon Route 53": "AWS DNS 웹 서비스",
    "AWS Elastic Load Balancing (ELB)": "AWS 로드 밸런서",
    "Amazon CloudFront": "AWS 콘텐츠 전송 네트워크(CDN)",
    "Amazon CloudWatch": "AWS 모니터링 서비스",
    "Amazon VPC": "AWS 가상 사설 클라우드",
    "Amazon API Gateway": "API 생성 및 관리 서비스",
    "Amazon SES": "AWS 이메일 전송 서비스",
    "Amazon SQS": "AWS 메시지 큐 서비스",
    "Amazon SNS": "AWS 알림 서비스",
    "Google Compute Engine": "Google Cloud 가상 머신",
    "Google App Engine": "Google Cloud 애플리케이션 플랫폼",
    "Google Kubernetes Engine": "Google Cloud 관리형 Kubernetes",
    "Google Cloud Storage": "Google Cloud 객체 스토리지",
    "Google BigQuery": "Google Cloud 데이터 웨어하우스",
    "Google Cloud Functions": "Google Cloud 서버리스 함수",
    "Google Cloud Build": "Google Cloud CI/CD 서비스",
    "Google Cloud Pub/Sub": "Google Cloud 메시징 서비스",
    "Google Cloud Dataflow": "Google Cloud 데이터 처리 서비스",
    "Google Cloud Datastore": "Google Cloud NoSQL 데이터베이스",
    "Google Cloud Bigtable": "Google Cloud NoSQL 빅데이터 데이터베이스",
    "Google Cloud DNS": "Google Cloud DNS 서비스",
    "Google Cloud Run": "Google Cloud 컨테이너 실행 서비스",
    "Azure Functions": "Azure 서버리스 함수",
    "Azure DevOps": "Azure 개발 및 배포 도구",
    "Azure Pipelines": "Azure CI/CD 파이프라인",
    "Azure App Service": "Azure 웹 앱 호스팅",
    "Azure Service Bus": "Azure 메시징 서비스",
    "Azure Active Directory": "Azure ID 및 액세스 관리",
    "Azure Storage": "Azure 클라우드 스토리지",
    "Azure Databricks": "Azure 분석 플랫폼",
    "Azure Machine Learning": "Azure ML 플랫폼",
    "Azure Application Insights": "Azure 애플리케이션 모니터링",
    "Azure Data Factory": "Azure 데이터 통합 서비스",
    "Azure Websites": "Azure 웹 사이트 호스팅 서비스",
    "Azure Kubernetes Service": "Azure 관리형 Kubernetes",
    "Vercel": "프론트엔드 배포 플랫폼",
    "Netlify": "정적 사이트 배포 플랫폼",
    "Linode": "개발자 친화적 클라우드 호스팅",
    "Red Hat OpenShift": "엔터프라이즈 Kubernetes 플랫폼",
    "Cloud Foundry": "오픈소스 클라우드 애플리케이션 플랫폼",
    "AWS Fargate": "서버리스 컨테이너 실행",
    "AWS CloudFormation": "인프라 자동화 서비스",
    "AWS IAM": "AWS 접근 권한 관리",
    "AWS Glue": "AWS 데이터 통합 서비스",
    "AWS Step Functions": "서버리스 워크플로우 오케스트레이션",
    "AWS CodePipeline": "CI/CD 파이프라인 서비스",
    "AWS CodeBuild": "관리형 빌드 서비스",
    "AWS CodeDeploy": "자동화된 배포 서비스",
    "AWS CodeCommit": "AWS Git 저장소",
    "AWS Amplify": "풀스택 애플리케이션 개발 플랫폼",
    "AWS Cloud9": "클라우드 IDE",
    "AWS CloudTrail": "AWS API 활동 로깅",
    "Amazon Cognito": "사용자 인증 및 권한 부여",
    "Amazon EKS": "AWS 관리형 Kubernetes",
    "Amazon EMR": "AWS 빅데이터 플랫폼",
    "Amazon Quicksight": "AWS 비즈니스 인텔리전스 서비스",
    "Amazon LightSail": "간단한 가상 서버",
    "Amazon ECR": "AWS 컨테이너 레지스트리",
    "Rackspace Cloud Servers": "Rackspace 클라우드 서버",
    "Render": "통합 클라우드 플랫폼",
    "Clever Cloud": "자동 확장 클라우드 플랫폼",

    # Mobile Development
    "React Native": "크로스 플랫폼 모바일 앱 프레임워크",
    "Flutter": "Google의 크로스 플랫폼 UI 프레임워크",
    "Android SDK": "Android 애플리케이션 개발 킷",
    "Android Studio": "Android 공식 IDE",
    "Xcode": "Apple 플랫폼 개발 IDE",
    "iOS": "Apple 모바일 운영체제",
    "Android OS": "Google 모바일 운영체제",
    "Ionic": "하이브리드 모바일 앱 프레임워크",
    "Xamarin": "크로스 플랫폼 모바일 개발 프레임워크",
    "Cordova": "Apache Cordova, 하이브리드 모바일 앱 플랫폼",
    "Apache Cordova": "하이브리드 모바일 앱 프레임워크",
    "NativeScript": "네이티브 모바일 앱 개발 프레임워크",
    "SwiftUI": "Swift 기반 UI 프레임워크",
    "Expo": "React Native 개발 플랫폼",
    "React Navigation": "React Native 네비게이션 라이브러리",
    "fastlane": "iOS 및 Android 자동화 도구",
    "TestFlight": "iOS 베타 테스팅 플랫폼",
    "CocoaPods": "iOS 의존성 관리자",
    "Android Room": "Android 로컬 데이터베이스 라이브러리",
    "Capacitor": "크로스 플랫폼 네이티브 런타임",
    "Vue Native": "Vue.js 기반 모바일 프레임워크",
    "Xamarin Forms": "Xamarin UI 프레임워크",
    "PhoneGap": "하이브리드 모바일 앱 개발 플랫폼",
    "Crashlytics": "모바일 앱 크래시 리포팅",
    "Firebase Cloud Messaging": "Firebase 푸시 알림 서비스",
    "Firebase Authentication": "Firebase 인증 서비스",

    # Testing
    "Jest": "JavaScript 테스팅 프레임워크",
    "Mocha": "JavaScript 테스트 프레임워크",
    "Jasmine": "JavaScript BDD 테스팅 프레임워크",
    "Cypress": "프론트엔드 E2E 테스팅 도구",
    "Selenium": "웹 브라우저 자동화 도구",
    "JUnit": "Java 단위 테스트 프레임워크",
    "pytest": "Python 테스팅 프레임워크",
    "RSpec": "Ruby BDD 테스팅 프레임워크",
    "PHPUnit": "PHP 단위 테스트 프레임워크",
    "Chai": "JavaScript assertion 라이브러리",
    "Karma": "JavaScript 테스트 러너",
    "Protractor": "Angular E2E 테스팅 프레임워크",
    "Puppeteer": "Headless Chrome Node.js API",
    "Enzyme": "React 컴포넌트 테스팅 유틸리티",
    "TestNG": "Java 테스팅 프레임워크",
    "xUnit": ".NET 단위 테스트 프레임워크",
    "NUnit": ".NET 테스팅 프레임워크",
    "Cucumber": "BDD 테스팅 프레임워크",
    "Codecov": "코드 커버리지 도구",
    "BrowserStack": "클라우드 브라우저 테스팅",
    "SinonJS": "JavaScript 테스트 스파이/스텁/모킹",
    "Mockito": "Java 모킹 프레임워크",
    "Testify": "Go 테스팅 toolkit",
    "SuperTest": "Node.js HTTP 테스팅",
    "jsdom": "JavaScript DOM 구현",
    "TestCafe": "Node.js E2E 테스팅",
    "Nightwatchjs": "Node.js E2E 테스팅 프레임워크",
    "WebdriverIO": "Node.js WebDriver 테스트 자동화",
    "Appium": "모바일 앱 자동화 테스팅",
    "Sauce Labs": "클라우드 테스팅 플랫폼",
    "Gatling": "부하 테스트 도구",
    "Locust": "Python 기반 부하 테스트 도구",
    "k6": "현대적인 부하 테스트 도구",
    "Apache JMeter": "부하 테스트 도구",
    "QUnit": "JavaScript 단위 테스트 프레임워크",
    "Capybara": "Ruby 웹 애플리케이션 테스트 프레임워크",
    "PhpSpec": "PHP SpecBDD 프레임워크",
    "ScalaTest": "Scala 테스팅 프레임워크",
    "Spock Framework": "Groovy 테스팅 프레임워크",
    "Robot Framework": "키워드 기반 테스트 자동화",
    "Istanbul": "JavaScript 코드 커버리지 도구",
    "LambdaTest": "클라우드 크로스 브라우저 테스팅",
    "Playwright": "크로스 브라우저 자동화",
    "react-testing-library": "React 테스팅 라이브러리",
    "Testrail": "테스트 케이스 관리 도구",
    "Gherkin": "BDD 테스트 시나리오 언어",

    # Build Tools
    "Webpack": "JavaScript 모듈 번들러",
    "Babel": "JavaScript 트랜스파일러",
    "npm": "Node.js 패키지 관리자",
    "Yarn": "빠른 JavaScript 패키지 관리자",
    "Gradle": "빌드 자동화 도구",
    "Maven": "Apache Maven, Java 프로젝트 관리 도구",
    "Apache Maven": "Java 빌드 및 의존성 관리 도구",
    "gulp": "JavaScript 태스크 러너",
    "Grunt": "JavaScript 태스크 러너",
    "Bower": "웹 패키지 관리자",
    "Vite": "차세대 프론트엔드 빌드 도구",
    "Parcel": "웹 애플리케이션 번들러",
    "rollup": "JavaScript 모듈 번들러",
    "Browserify": "브라우저용 Node.js 스타일 모듈 번들러",
    "RequireJS": "JavaScript 모듈 로더",
    "Lerna": "모노레포 관리 도구",
    "Esbuild": "고속 JavaScript 번들러",
    "CMake": "크로스 플랫폼 빌드 시스템",
    "NuGet": ".NET 패키지 관리자",
    "RubyGems": "Ruby 패키지 관리자",
    "PyPI": "Python 패키지 인덱스",
    "Composer": "PHP 의존성 관리자",
    "Bundler": "Ruby 의존성 관리자",
    "CocoaPods": "iOS 의존성 관리자",
    "Homebrew": "macOS 패키지 관리자",
    "pip": "Python 패키지 설치 도구",
    "Make": "빌드 자동화 도구",
    "Bazel": "빌드 및 테스트 도구",

    # Code Quality
    "ESLint": "JavaScript 린팅 도구",
    "Prettier": "코드 포맷터",
    "TSLint": "TypeScript 린팅 도구 (deprecated)",
    "SonarQube": "코드 품질 분석 플랫폼",
    "RuboCop": "Ruby 코드 스타일 검사기",
    "Pylint": "Python 코드 분석 도구",
    "flake8": "Python 코드 스타일 검사기",
    "JSHint": "JavaScript 코드 품질 도구",
    "Stylelint": "CSS 린팅 도구",
    "SonarLint": "IDE용 코드 품질 플러그인",
    "PHPStan": "PHP 정적 분석 도구",
    "FindBugs": "Java 버그 패턴 탐지기",
    "Codacy": "자동화된 코드 리뷰",
    "Code Climate": "코드 품질 분석 플랫폼",

    # Monitoring & Logging
    "New Relic": "애플리케이션 성능 모니터링(APM)",
    "Datadog": "모니터링 및 분석 플랫폼",
    "Sentry": "에러 추적 및 모니터링",
    "Grafana": "메트릭 시각화 및 대시보드",
    "Prometheus": "오픈소스 모니터링 시스템",
    "Kibana": "Elasticsearch 시각화 도구",
    "Logstash": "로그 수집 및 처리 파이프라인",
    "ELK": "Elasticsearch, Logstash, Kibana 스택",
    "Splunk": "로그 분석 및 모니터링 플랫폼",
    "Graylog": "로그 관리 플랫폼",
    "Fluentd": "로그 수집 및 전송 도구",
    "Nagios": "인프라 모니터링 도구",
    "Zabbix": "엔터프라이즈 모니터링 솔루션",
    "Pingdom": "웹사이트 모니터링 서비스",
    "StatusPage.io": "상태 페이지 서비스",
    "UptimeRobot": "웹사이트 가동 시간 모니터링",
    "Rollbar": "실시간 에러 추적",
    "Bugsnag": "에러 모니터링 플랫폼",
    "TrackJS": "JavaScript 에러 추적",
    "LogRocket": "프론트엔드 모니터링",
    "Airbrake": "에러 및 성능 모니터링",
    "Papertrail": "클라우드 로그 관리",
    "Loggly": "로그 관리 서비스",
    "Logentries": "로그 관리 및 분석",
    "AppDynamics": "애플리케이션 성능 관리",
    "Dynatrace": "소프트웨어 인텔리전스 플랫폼",
    "Loki": "로그 집계 시스템",
    "Stackdriver": "Google Cloud 모니터링",
    "Netdata": "실시간 성능 모니터링",
    "Telegraf": "메트릭 수집 에이전트",
    "StatsD": "메트릭 집계 데몬",
    "Graphite": "메트릭 저장 및 시각화",
    "Jaeger": "분산 추적 시스템",
    "OpenCensus": "분산 추적 및 메트릭 수집",
    "Splunk Cloud": "클라우드 기반 Splunk",

    # Message Brokers
    "RabbitMQ": "오픈소스 메시지 브로커",
    "Kafka": "분산 스트리밍 플랫폼",
    "ActiveMQ": "오픈소스 메시지 브로커",
    "Kafka Streams": "Kafka 스트림 처리 라이브러리",
    "Zookeeper": "분산 시스템 조정 서비스",
    "NATS": "클라우드 네이티브 메시징 시스템",
    "NSQ": "실시간 분산 메시징 플랫폼",
    "ZeroMQ": "고성능 비동기 메시징 라이브러리",

    # API & GraphQL
    "GraphQL": "API 쿼리 언어",
    "Postman": "API 개발 및 테스팅 도구",
    "Swagger UI": "API 문서화 도구",
    "Apollo": "GraphQL 플랫폼",
    "Insomnia REST Client": "REST API 클라이언트",
    "Apigee": "API 관리 플랫폼",
    "Kong": "API 게이트웨이",
    "Apiary": "API 디자인 및 문서화",
    "Paw": "macOS API 테스팅 도구",

    # CMS
    "WordPress": "오픈소스 콘텐츠 관리 시스템",
    "Drupal": "PHP 기반 CMS",
    "Joomla!": "오픈소스 CMS",
    "Ghost": "Node.js 기반 블로그 플랫폼",
    "Contentful": "Headless CMS",
    "Strapi": "오픈소스 Headless CMS",
    "Netlify CMS": "Git 기반 Headless CMS",
    "Sanity": "구조화된 콘텐츠 플랫폼",
    "Prismic": "Headless CMS",

    # E-commerce
    "Shopify": "전자상거래 플랫폼",
    "WooCommerce": "WordPress 전자상거래 플러그인",
    "Magento": "오픈소스 전자상거래 플랫폼",
    "BigCommerce": "SaaS 전자상거래 플랫폼",
    "PrestaShop": "오픈소스 전자상거래 솔루션",
    "OpenCart": "PHP 전자상거래 플랫폼",

    # Data Science & ML
    "TensorFlow": "오픈소스 머신러닝 프레임워크",
    "PyTorch": "딥러닝 프레임워크",
    "Keras": "고수준 신경망 API",
    "scikit-learn": "Python 머신러닝 라이브러리",
    "Pandas": "데이터 분석 라이브러리",
    "NumPy": "수치 계산 라이브러리",
    "Jupyter": "인터랙티브 컴퓨팅 환경",
    "Matplotlib": "Python 플로팅 라이브러리",
    "SciPy": "과학 컴퓨팅 라이브러리",
    "OpenCV": "컴퓨터 비전 라이브러리",
    "Anaconda": "데이터 과학 플랫폼",
    "Apache Spark": "빅데이터 처리 엔진",
    "Hadoop": "분산 데이터 처리 프레임워크",
    "Apache Flink": "스트림 처리 프레임워크",
    "Apache Beam": "통합 배치 및 스트리밍 모델",
    "Apache Hive": "데이터 웨어하우스 인프라",
    "Airflow": "워크플로우 관리 플랫폼",
    "MLflow": "ML 라이프사이클 플랫폼",
    "Kubeflow": "Kubernetes 기반 ML 툴킷",
    "LangChain": "LLM 애플리케이션 개발 프레임워크",
    "OpenAI": "AI 연구 및 API 제공",
    "ChatGPT": "OpenAI 대화형 AI",
    "PySpark": "Spark Python API",
    "IPython": "대화형 Python 셸",
    "SpaCy": "자연어 처리 라이브러리",
    "Pillow": "Python 이미지 처리 라이브러리",
    "scikit-image": "이미지 처리 라이브러리",
    "TensorFlow.js": "JavaScript 머신러닝 라이브러리",
    "CUDA": "NVIDIA GPU 병렬 컴퓨팅 플랫폼",
    "MATLAB": "수치 계산 소프트웨어",
    "RStudio": "R 통합 개발 환경",
    "Dialogflow": "대화형 AI 플랫폼",
    "Databricks": "통합 분석 플랫폼",
    "Streamlit": "ML/데이터 앱 프레임워크",
    "dbt": "데이터 변환 도구",

    # Web Servers
    "NGINX": "고성능 웹 서버 및 리버스 프록시",
    "Apache HTTP Server": "오픈소스 웹 서버",
    "Apache Tomcat": "Java 서블릿 컨테이너",
    "Microsoft IIS": "Windows 웹 서버",
    "Gunicorn": "Python WSGI HTTP 서버",
    "Caddy": "자동 HTTPS 웹 서버",
    "HAProxy": "고성능 로드 밸런서",
    "Varnish": "HTTP 캐시 서버",
    "LiteSpeed": "고성능 웹 서버",
    "OpenResty": "Nginx 기반 웹 플랫폼",
    "Passenger": "애플리케이션 서버",
    "Puma": "Ruby 웹 서버",
    "Unicorn": "Ruby HTTP 서버",
    "uWSGI": "애플리케이션 서버 컨테이너",
    "GlassFish": "Java EE 애플리케이션 서버",
    "JBoss": "Java 애플리케이션 서버",
    "Jetty": "Java 웹 서버 및 서블릿 컨테이너",
    "Cowboy": "Erlang HTTP 서버",
    "PM2": "Node.js 프로세스 관리자",

    # CSS Frameworks
    "Bootstrap": "인기있는 CSS 프레임워크",
    "Tailwind CSS": "유틸리티 우선 CSS 프레임워크",
    "Material-UI": "React Material Design 컴포넌트",
    "Ant Design": "엔터프라이즈급 UI 디자인 시스템",
    "Bulma": "현대적인 CSS 프레임워크",
    "Foundation": "반응형 프론트엔드 프레임워크",
    "Semantic UI": "사용자 인터페이스 프레임워크",
    "Material Design": "Google의 디자인 시스템",
    "Material Design for Angular": "Angular Material Design",
    "Angular Material": "Angular 컴포넌트 라이브러리",
    "Vuetify": "Vue.js Material Design 컴포넌트",
    "Material Design Lite": "경량 Material Design",
    "Materialize": "CSS 프레임워크",
    "Chakra UI": "React 컴포넌트 라이브러리",
    "styled-components": "React CSS-in-JS 라이브러리",
    "Emotion": "CSS-in-JS 라이브러리",
    "Sass": "CSS 전처리기",
    "Less": "CSS 전처리기",
    "PostCSS": "CSS 변환 도구",
    "Stylus": "CSS 전처리기",
    "Autoprefixer": "CSS 자동 벤더 프리픽스",
    "UIkIt": "프론트엔드 프레임워크",
    "PrimeNg": "Angular UI 컴포넌트",
    "Kendo UI": "JavaScript UI 컴포넌트",
    "Bootstrap Vue": "Vue.js용 Bootstrap",
    "Semantic UI React": "React용 Semantic UI",
    "reactstrap": "React용 Bootstrap 컴포넌트",
    "Ionicons": "프리미엄 아이콘 세트",
    "Normalize.css": "CSS 리셋 라이브러리",

    # JavaScript Libraries
    "jQuery": "빠르고 작은 JavaScript 라이브러리",
    "React": "UI 구축을 위한 JavaScript 라이브러리",
    "Lodash": "JavaScript 유틸리티 라이브러리",
    "axios": "Promise 기반 HTTP 클라이언트",
    "Moment.js": "날짜 처리 라이브러리",
    "date-fns": "모던 JavaScript 날짜 유틸리티",
    "D3.js": "데이터 시각화 라이브러리",
    "Chart.js": "간단한 차트 라이브러리",
    "Highcharts": "인터랙티브 차트 라이브러리",
    "three.js": "3D 그래픽 라이브러리",
    "Socket.IO": "실시간 양방향 통신 라이브러리",
    "RxJS": "반응형 프로그래밍 라이브러리",
    "Redux": "JavaScript 상태 관리 라이브러리",
    "React Redux": "React용 Redux 바인딩",
    "redux-thunk": "Redux 비동기 미들웨어",
    "redux-saga": "Redux 사이드 이펙트 관리",
    "MobX": "간단하고 확장 가능한 상태 관리",
    "vuex": "Vue.js 상태 관리 라이브러리",
    "Backbone.js": "JavaScript MVC 프레임워크",
    "Handlebars.js": "JavaScript 템플릿 엔진",
    "Mustache": "로직 없는 템플릿 시스템",
    "Underscore": "JavaScript 유틸리티 라이브러리",
    "Immutable.js": "불변 데이터 구조 라이브러리",
    "Ramda": "함수형 JavaScript 라이브러리",
    "React Router": "React 라우팅 라이브러리",
    "Vue Router": "Vue.js 라우터",
    "React Hot Loader": "React 컴포넌트 핫 리로딩",
    "Modernizr": "HTML5/CSS3 기능 탐지 라이브러리",
    "Leaflet": "인터랙티브 지도 라이브러리",
    "Mapbox": "커스터마이징 가능한 지도 플랫폼",
    "clipboard.js": "클립보드 복사 라이브러리",
    "Select2": "jQuery 기반 셀렉트 박스",
    "DataTables": "jQuery 테이블 플러그인",
    "fancybox": "jQuery 라이트박스 플러그인",
    "SweetAlert": "JavaScript 팝업 박스",
    "highlight.js": "구문 강조 라이브러리",
    "Lottie": "애니메이션 라이브러리",
    "Plotly.js": "차트 및 그래프 라이브러리",
    "Recharts": "React 차트 라이브러리",
    "C3.js": "D3 기반 재사용 가능한 차트 라이브러리",
    "Flux": "애플리케이션 아키텍처 패턴",
    "reselect": "Redux selector 라이브러리",
    "ws": "Node.js WebSocket 라이브러리",
    "Nodemailer": "Node.js 이메일 전송 라이브러리",
    "LiveReload": "자동 브라우저 새로고침",
    "nodemon": "Node.js 자동 재시작 도구",
    "Formik": "React 폼 라이브러리",
    "i18next": "국제화 프레임워크",
    "Prototype": "JavaScript 프레임워크",
    "YUI Library": "Yahoo UI 라이브러리",
    "MooTools": "JavaScript 프레임워크",
    "Dojo": "JavaScript 툴킷",
    "jQuery UI": "jQuery UI 위젯",
    "jQuery Mobile": "모바일 최적화 jQuery 프레임워크",
    "Knockout": "MVVM 패턴 JavaScript 라이브러리",
    "Polymer": "웹 컴포넌트 라이브러리",
    "Animate.css ": "CSS 애니메이션 라이브러리",
    "OpenLayers": "웹 지도 라이브러리",
    "OpenStreetMap": "오픈소스 지도 프로젝트",

    # Static Site Generators
    "Jekyll": "Ruby 기반 정적 사이트 생성기",
    "Hugo": "Go 기반 정적 사이트 생성기",
    "Hexo": "Node.js 블로그 프레임워크",
    "VuePress": "Vue 기반 정적 사이트 생성기",
    "Docusaurus": "문서 사이트 생성기",
    "Gitbook": "문서 작성 도구",

    # IDEs & Editors
    "Visual Studio Code": "Microsoft의 오픈소스 코드 에디터",
    "Visual Studio": "Microsoft 통합 개발 환경",
    "IntelliJ IDEA": "JetBrains Java IDE",
    "PyCharm": "JetBrains Python IDE",
    "WebStorm": "JetBrains JavaScript IDE",
    "PhpStorm": "JetBrains PHP IDE",
    "Android Studio": "Android 공식 IDE",
    "Xcode": "Apple 플랫폼 개발 IDE",
    "Sublime Text": "정교한 텍스트 에디터",
    "Atom": "GitHub의 해커블 텍스트 에디터",
    "Vim": "고급 텍스트 에디터",
    "Neovim": "Vim 포크 프로젝트",
    "Emacs": "확장 가능한 텍스트 에디터",
    "Eclipse": "오픈소스 IDE",
    "NetBeans IDE": "Java IDE",
    "GoLand": "JetBrains Go IDE",
    "CLion": "JetBrains C/C++ IDE",
    "RubyMine": "JetBrains Ruby IDE",
    "DataGrip": "JetBrains 데이터베이스 IDE",
    "JetBrains Rider": ".NET IDE",
    "Brackets": "웹 디자인 중심 에디터",
    "Notepad++": "Windows 텍스트 에디터",
    "ReSharper": "Visual Studio .NET 확장",
    "vscode.dev": "브라우저 기반 VS Code",
    "Red Hat Codeready Workspaces": "Kubernetes 네이티브 IDE",

    # Design Tools
    "Figma": "협업 디자인 도구",
    "Sketch": "디지털 디자인 툴킷",
    "Adobe Photoshop": "이미지 편집 소프트웨어",
    "Adobe Illustrator": "벡터 그래픽 에디터",
    "Adobe XD": "UI/UX 디자인 도구",
    "InVision": "디지털 제품 디자인 플랫폼",
    "Zeplin": "디자인 협업 도구",
    "Balsamiq": "와이어프레임 도구",
    "Adobe InDesign": "출판 디자인 소프트웨어",
    "Blender": "3D 제작 소프트웨어",
    "Framer": "인터랙티브 디자인 도구",
    "Miro": "온라인 협업 화이트보드",
    "Lucidchart": "다이어그램 작성 도구",
    "drawio": "무료 다이어그램 소프트웨어",

    # Collaboration Tools
    "Slack": "팀 커뮤니케이션 플랫폼",
    "Jira": "프로젝트 관리 및 이슈 추적",
    "Trello": "Kanban 보드 기반 협업 도구",
    "Asana": "업무 관리 플랫폼",
    "Confluence": "팀 협업 및 문서화 도구",
    "Notion": "올인원 워크스페이스",
    "Microsoft Teams": "협업 플랫폼",
    "Discord": "음성/텍스트 커뮤니케이션 플랫폼",
    "Zoom": "화상 회의 플랫폼",
    "Google Meet": "화상 회의 서비스",
    "Mattermost": "오픈소스 메시징 플랫폼",
    "RocketChat": "오픈소스 커뮤니케이션 플랫폼",
    "Basecamp": "프로젝트 관리 도구",
    "ClickUp": "생산성 플랫폼",
    "monday.com": "업무 운영 시스템",
    "Linear": "이슈 추적 도구",
    "ZenHub": "GitHub 프로젝트 관리",
    "Pivotal Tracker": "애자일 프로젝트 관리",
    "Gitter": "개발자 커뮤니티 채팅",
    "Zulip": "팀 채팅 소프트웨어",
    "HipChat": "팀 채팅 서비스 (deprecated)",
    "Skype": "화상 통화 소프트웨어",
    "Telegram ": "메시징 앱",
    "WhatsApp": "메시징 앱",
    "Jitsi": "오픈소스 화상 회의",
    "Calendly": "일정 조율 도구",

    # Documentation
    "Markdown": "경량 마크업 언어",
    "Swagger UI": "API 문서화 도구",
    "Storybook": "UI 컴포넌트 개발 환경",
    "jsdoc": "JavaScript 문서화 도구",
    "Sphinx": "Python 문서화 도구",
    "Docusaurus": "문서 사이트 생성기",
    "GitLab Pages": "GitLab 정적 사이트 호스팅",
    "GitHub Pages": "GitHub 정적 사이트 호스팅",

    # Authentication & Security
    "Auth0": "인증 및 권한 부여 플랫폼",
    "OAuth2": "인증 프로토콜",
    "Keycloak": "오픈소스 IAM 솔루션",
    "Okta": "ID 관리 서비스",
    "JSON Web Token": "JWT, 안전한 정보 전송 표준",
    "Passport": "Node.js 인증 미들웨어",
    "Devise": "Rails 인증 솔루션",
    "OmniAuth": "Ruby 인증 프레임워크",
    "OpenSSL": "암호화 라이브러리",
    "Let's Encrypt": "무료 SSL 인증서",
    "Vault": "시크릿 관리 도구",
    "1Password": "비밀번호 관리자",
    "bitwarden": "오픈소스 비밀번호 관리자",
    "LastPass": "비밀번호 관리 서비스",

    # Payment
    "Stripe": "온라인 결제 플랫폼",
    "PayPal": "온라인 결제 시스템",
    "Braintree": "결제 게이트웨이",

    # Email Services
    "Gmail": "Google 이메일 서비스",
    "Mailchimp": "이메일 마케팅 플랫폼",
    "Twilio SendGrid": "이메일 전송 서비스",
    "Mailgun": "이메일 API 서비스",
    "Mandrill": "트랜잭션 이메일 API",
    "Postmark": "트랜잭션 이메일 서비스",
    "Amazon SES": "AWS 이메일 서비스",
    "Microsoft Outlook": "이메일 클라이언트",
    "Zoho Mail": "이메일 호스팅 서비스",

    # Analytics
    "Google Analytics": "웹 분석 서비스",
    "Mixpanel": "제품 분석 플랫폼",
    "Amplitude": "제품 분석 도구",
    "Segment": "고객 데이터 플랫폼",
    "Heap": "자동 이벤트 추적 분석",
    "FullStory": "디지털 경험 인텔리전스",
    "Hotjar": "사용자 행동 분석",
    "Crazy Egg": "히트맵 및 A/B 테스팅",
    "Optimizely": "실험 플랫폼",
    "Visual Website Optimizer": "A/B 테스팅 도구",
    "Google Tag Manager": "태그 관리 시스템",
    "Matomo": "오픈소스 웹 분석",
    "Piwik": "웹 분석 플랫폼 (Matomo 이전 이름)",
    "Clicky": "실시간 웹 분석",
    "Chartbeat": "실시간 분석 도구",
    "AddThis": "소셜 공유 도구",
    "Quantcast": "측정 및 광고 플랫폼",
    "KISSmetrics": "고객 분석 플랫폼",
    "Facebook Pixel": "Facebook 광고 추적",
    "Google Ads": "Google 광고 플랫폼",
    "Facebook Ads": "Facebook 광고 플랫폼",
    "Google AdSense": "광고 수익화 플랫폼",
    "SEMrush": "SEO 도구",
    "Google Search Console": "웹사이트 검색 성능 도구",

    # Content & Media
    "Font Awesome": "아이콘 툴킷",
    "Google Fonts": "웹 폰트 라이브러리",
    "Typekit": "Adobe 웹 폰트 서비스",
    "Cloudinary": "이미지 및 비디오 관리",
    "imgix": "이미지 최적화 서비스",

    # CDN
    "CloudFlare": "웹 성능 및 보안 서비스",
    "Amazon CloudFront": "AWS CDN",
    "Fastly": "엣지 클라우드 플랫폼",
    "MaxCDN": "콘텐츠 전송 네트워크",
    "Akamai": "CDN 및 클라우드 서비스",
    "Incapsula": "웹 애플리케이션 보안",

    # DNS
    "Amazon Route 53": "AWS DNS 서비스",
    "CloudFlare": "DNS 및 보안 서비스",
    "DNS Made Easy": "관리형 DNS 서비스",
    "Dyn": "인터넷 성능 관리",

    # CRM & Marketing
    "Salesforce": "CRM 플랫폼",
    "Salesforce Sales Cloud": "영업 자동화 CRM",
    "Salesforce Commerce Cloud": "전자상거래 플랫폼",
    "Salesforce Marketing Cloud": "마케팅 자동화 플랫폼",
    "HubSpot": "인바운드 마케팅 플랫폼",
    "Marketo": "마케팅 자동화 소프트웨어",
    "Pardot": "B2B 마케팅 자동화",
    "Zendesk": "고객 서비스 소프트웨어",
    "Intercom": "고객 메시징 플랫폼",
    "Freshdesk": "고객 지원 소프트웨어",
    "Help Scout": "고객 서비스 플랫폼",
    "Drift": "대화형 마케팅 플랫폼",
    "Olark": "라이브 채팅 소프트웨어",
    "Zopim": "라이브 채팅 소프트웨어 (Zendesk Chat)",
    "LiveChat": "고객 서비스 소프트웨어",
    "tawk.to": "무료 라이브 채팅",
    "Disqus": "댓글 플랫폼",
    "Customer.io": "자동화된 메시징 플랫폼",
    "OneSignal": "푸시 알림 서비스",
    "Pusher": "실시간 API",
    "PubNub": "실시간 통신 플랫폼",
    "SendBird": "채팅 및 메시징 SDK",
    "Stream": "피드 및 채팅 API",
    "Pipedrive": "영업 CRM",
    "Zoho CRM": "CRM 소프트웨어",
    "UserVoice": "고객 피드백 소프트웨어",
    "Typeform": "온라인 폼 빌더",
    "SumoMe": "웹사이트 트래픽 도구",
    "Unbounce": "랜딩 페이지 빌더",

    # Business Intelligence
    "Tableau": "데이터 시각화 소프트웨어",
    "Power BI": "비즈니스 분석 서비스",
    "Looker": "비즈니스 인텔리전스 플랫폼",
    "Metabase": "오픈소스 BI 도구",
    "Redash": "데이터 시각화 도구",
    "Chartio": "클라우드 BI 플랫폼",
    "Superset": "데이터 탐색 플랫폼",
    "Data Studio": "Google 데이터 시각화 도구",
    "Dataform": "데이터 모델링 플랫폼",

    # Web Hosting
    "Heroku": "클라우드 애플리케이션 플랫폼",
    "Netlify": "정적 사이트 호스팅",
    "Vercel": "프론트엔드 클라우드 플랫폼",
    "GitHub Pages": "정적 사이트 호스팅",
    "Squarespace": "웹사이트 빌더",
    "Wix": "웹사이트 빌더",
    "Weebly": "웹사이트 빌더",
    "Webflow": "노코드 웹 디자인 도구",
    "Bubble": "노코드 애플리케이션 플랫폼",
    "Render": "클라우드 플랫폼",
    "Namecheap": "도메인 및 호스팅",
    "GoDaddy": "도메인 및 호스팅",
    "OVH": "클라우드 및 호스팅",

    # Operating Systems
    "Linux": "오픈소스 운영체제",
    "Ubuntu": "Linux 배포판",
    "Debian": "안정적인 Linux 배포판",
    "CentOS": "엔터프라이즈급 Linux",
    "Red Hat Enterprise Linux (RHEL)": "상업용 Linux",
    "Fedora": "커뮤니티 지원 Linux",
    "Alpine Linux": "보안 중심 경량 Linux",
    "Arch Linux": "경량 유연한 Linux",
    "Linux Mint": "사용자 친화적 Linux",
    "Kali Linux": "보안 테스팅 Linux",
    "macOS": "Apple 데스크톱 운영체제",
    "Mac OS X": "Apple 데스크톱 OS (레거시)",
    "Windows": "Microsoft 운영체제",
    "Windows 10": "Windows 버전 10",
    "Windows Server ": "Windows 서버 OS",
    "CoreOS": "컨테이너 최적화 Linux",

    # Virtualization
    "VirtualBox": "오픈소스 가상화 소프트웨어",
    "Vagrant": "가상 개발 환경 도구",
    "VMware vSphere": "가상화 플랫폼",
    "Proxmox VE": "오픈소스 가상화 관리",
    "Docker Machine": "Docker 호스트 프로비저닝",
    "boot2docker": "경량 Docker 환경",

    # Configuration Management
    "Ansible": "IT 자동화 도구",
    "Chef": "인프라 자동화 플랫폼",
    "Puppet Labs": "인프라 자동화",
    "Salt": "인프라 관리 소프트웨어",
    "Terraform": "인프라 코드화 도구",
    "Packer": "머신 이미지 빌더",
    "Consul": "서비스 메시 솔루션",
    "etcd": "분산 키-값 저장소",

    # Container Orchestration
    "Kubernetes": "컨테이너 오케스트레이션",
    "Docker Swarm": "Docker 클러스터링",
    "Rancher": "컨테이너 관리 플랫폼",
    "Nomad": "워크로드 오케스트레이터",
    "Portainer": "컨테이너 관리 UI",
    "Helm": "Kubernetes 패키지 매니저",

    # Service Mesh
    "Istio": "서비스 메시",
    "Envoy": "프록시 및 커뮤니케이션 버스",
    "Traefik": "클라우드 네이티브 엣지 라우터",
    "Linkerd": "서비스 메시",
    "Zuul": "엣지 서비스",

    # CI/CD
    "Jenkins": "오픈소스 자동화 서버",
    "Travis CI": "CI 서비스",
    "CircleCI": "CI/CD 플랫폼",
    "GitLab CI": "GitLab CI/CD",
    "Azure DevOps": "개발자 서비스",
    "Azure Pipelines": "CI/CD 서비스",
    "Bitbucket Pipelines": "Bitbucket CI/CD",
    "TeamCity": "JetBrains CI 서버",
    "Bamboo": "Atlassian CI 서버",
    "Codeship": "CI/CD 플랫폼",
    "Drone.io": "컨테이너 네이티브 CI",
    "GoCD": "오픈소스 CI/CD",
    "Concourse": "CI 시스템",
    "Spinnaker": "멀티 클라우드 CD 플랫폼",
    "Argo": "Kubernetes 네이티브 워크플로우",
    "Jenkins X": "Kubernetes용 CI/CD",
    "Octopus Deploy": ".NET 배포 자동화",
    "Buddy": "웹 개발자 자동화",
    "wercker": "컨테이너 CI/CD",
    "Bitrise": "모바일 CI/CD",

    # Artifact Repository
    "Docker Hub": "Docker 이미지 레지스트리",
    "JFrog Artifactory": "아티팩트 저장소",
    "Sonatype Nexus": "저장소 관리자",

    # Database Tools
    "DBeaver": "유니버설 데이터베이스 도구",
    "MySQL WorkBench": "MySQL GUI 도구",
    "phpMyAdmin": "MySQL 웹 관리",
    "MongoDB Compass": "MongoDB GUI",
    "Sequel Pro": "macOS MySQL 클라이언트",
    "dbForge Studio for MySQL": "MySQL 개발 도구",
    "dbForge Studio for PostgreSQL": "PostgreSQL 개발 도구",
    "dbForge Studio for Oracle": "Oracle 개발 도구",
    "Microsoft SQL Server Management Studio": "SQL Server 관리 도구",

    # ORM & Database Libraries
    "Hibernate": "Java ORM 프레임워크",
    "Sequelize": "Node.js ORM",
    "SQLAlchemy": "Python SQL 툴킷",
    "TypeORM": "TypeScript ORM",
    "Prisma": "차세대 ORM",
    "Mongoose": "MongoDB ODM",
    "MyBatis": "Java 퍼시스턴스 프레임워크",
    "Entity Framework": ".NET ORM",
    "Doctrine 2": "PHP ORM",
    "Knex.js": "SQL 쿼리 빌더",
    "Slick": "Scala 데이터베이스 라이브러리",
    "Spring Data": "Spring 데이터 액세스",
    "ent": "Go 엔티티 프레임워크",

    # Migration Tools
    "Liquibase": "데이터베이스 스키마 마이그레이션",
    "Flyway": "데이터베이스 마이그레이션 도구",

    # Template Engines
    "Jinja": "Python 템플릿 엔진",
    "Handlebars.js": "JavaScript 템플릿",
    "Mustache": "로직 없는 템플릿",
    "Pug": "Node.js 템플릿 엔진",
    "EJS": "임베디드 JavaScript 템플릿",
    "Twig": "PHP 템플릿 엔진",
    "Thymeleaf": "Java 템플릿 엔진",
    "Smarty": "PHP 템플릿 엔진",
    "HAML": "HTML 추상화 마크업",

    # Search
    "Elasticsearch": "검색 및 분석 엔진",
    "Algolia": "검색 API 플랫폼",
    "Solr": "엔터프라이즈 검색 플랫폼",

    # Workflow & Automation
    "Zapier": "자동화 플랫폼",
    "IFTTT": "자동화 서비스",
    "n8n": "워크플로우 자동화",

    # Feature Flags
    "LaunchDarkly": "기능 플래그 플랫폼",

    # Communication APIs
    "Twilio": "클라우드 통신 플랫폼",
    "Nexmo": "통신 API (Vonage)",
    "Telegram Bot API": "Telegram 봇 API",

    # Storage & CDN
    "Amazon S3": "AWS 객체 스토리지",
    "Google Cloud Storage": "Google 객체 스토리지",
    "Azure Storage": "Azure 클라우드 스토리지",
    "Dropbox": "클라우드 저장소",
    "Google Drive": "클라우드 저장소",
    "OneDrive": "Microsoft 클라우드 저장소",
    "Box": "클라우드 콘텐츠 관리",
    "Nextcloud": "자체 호스팅 클라우드",

    # Productivity
    "G Suite": "Google 비즈니스 도구",
    "Google Workspace": "Google 협업 도구",
    "Microsoft 365": "Microsoft 생산성 도구",
    "Microsoft SharePoint": "협업 플랫폼",
    "Microsoft Excel": "스프레드시트 소프트웨어",
    "Google Sheets": "온라인 스프레드시트",
    "Google Docs": "온라인 문서 편집기",
    "Google": "검색 엔진 및 서비스",
    "Airtable": "클라우드 협업 서비스",
    "PagerDuty": "인시던트 관리 플랫폼",
    "OpsGenie": "인시던트 관리",

    # Live Editing & Preview
    "CodeMirror": "브라우저 코드 에디터",
    "TinyMCE": "WYSIWYG 에디터",
    "ngrok": "로컬 서버 공개 도구",

    # Terminal
    "iTerm2": "macOS 터미널",
    "Oh My ZSH": "Zsh 설정 관리자",
    "Zsh (Z shell)": "확장된 Bourne 셸",
    "GNU Bash": "Bourne Again Shell",
    "Shell": "명령 줄 인터페이스",
    "PowerShell": "Windows 자동화 프레임워크",

    # Version Control Tools
    "SourceTree": "Git GUI 클라이언트",
    "GitKraken": "Git GUI 클라이언트",
    "Tower": "Git 클라이언트",
    "hub": "GitHub용 Git 래퍼",
    "Gitea": "자체 호스팅 Git 서비스",
    "Gogs": "경량 자체 호스팅 Git",
    "Mercurial": "분산 버전 관리",
    "Phabricator": "소프트웨어 개발 플랫폼",

    # Package Managers
    "npm": "Node.js 패키지 관리자",
    "Yarn": "JavaScript 패키지 관리자",
    "pip": "Python 패키지 설치 도구",
    "Composer": "PHP 의존성 관리자",
    "Bundler": "Ruby 의존성 관리자",
    "NuGet": ".NET 패키지 관리자",
    "RubyGems": "Ruby 패키지 관리자",
    "CocoaPods": "iOS 의존성 관리자",
    "Homebrew": "macOS 패키지 관리자",

    # Other Libraries & Frameworks
    "Spring": "Java 애플리케이션 프레임워크",
    "Spring Framework": "Java 엔터프라이즈 프레임워크",
    "Spring Boot": "Spring 기반 마이크로서비스",
    "Spring Cloud": "분산 시스템 패턴",
    "Spring MVC": "Spring 웹 MVC",
    "Spring Security": "인증 및 권한 프레임워크",
    ".NET": "Microsoft 개발 플랫폼",
    ".NET Core": "크로스 플랫폼 .NET",
    "Java EE": "Java 엔터프라이즈 에디션",
    "Java 8": "Java 버전 8",
    "Dapper": ".NET 마이크로 ORM",
    "Castle Core": ".NET 라이브러리",
    "Polly": ".NET 복원력 라이브러리",
    "AutoFac": ".NET IoC 컨테이너",
    "Owin": "웹 서버 및 앱 인터페이스",
    "SignalR": "실시간 웹 기능",
    "Microsoft Bot Framework": "봇 빌딩 프레임워크",
    "Blazor": ".NET 웹 프레임워크",
    "Retrofit": "Android HTTP 클라이언트",
    "RxJava": "반응형 확장 Java",
    "guava": "Google Java 라이브러리",
    "Jackson": "JSON 프로세서",
    "Akka": "액터 기반 동시성 툴킷",
    "Netty": "비동기 이벤트 기반 네트워크",
    "Apache Camel": "통합 프레임워크",
    "Apache FreeMarker": "Java 템플릿 엔진",
    "Logback": "Java 로깅 프레임워크",
    "SLF4J": "Java 로깅 파사드",
    "Log4j": "Java 로깅 유틸리티",
    "JavaFX": "Java GUI 툴킷",
    "Protobuf": "프로토콜 버퍼",
    "gRPC": "고성능 RPC 프레임워크",
    "Avro": "데이터 직렬화 시스템",
    "Apache Storm": "실시간 계산 시스템",
    "Apache Mesos": "클러스터 관리자",
    "Hazelcast": "인메모리 데이터 그리드",
    "Ehcache": "Java 캐시 라이브러리",
    "Hystrix": "지연 및 장애 허용 라이브러리",
    "Eureka": "서비스 레지스트리",
    "WebRTC": "실시간 통신",
    "MQTT": "경량 메시징 프로토콜",
    "Celery": "Python 비동기 작업 큐",
    "Sidekiq": "Ruby 백그라운드 작업",
    "Hangfire": ".NET 백그라운드 작업",
    "Scrapy": "Python 웹 크롤링 프레임워크",
    "Memcached": "분산 메모리 캐싱",
    "Varnish": "HTTP 가속기",
    "Aerospike": "NoSQL 데이터베이스",
    "PostGIS": "PostgreSQL 공간 확장",
    "Minio": "오픈소스 객체 스토리지",
    "Realm": "모바일 데이터베이스",
    "Serverless": "서버리스 프레임워크",
    "Pulumi": "인프라 코드화",
    "AWS CloudFormation": "인프라 템플릿",
    "Terraform Registry": "Terraform 모듈 레지스트리",

    # Game Development
    "Unity": "게임 엔진",
    "Unreal Engine": "3D 게임 엔진",
    "Godot": "오픈소스 게임 엔진",
    "GameMaker": "2D 게임 개발 도구",
    "Love2D": "2D 게임 프레임워크",
    "MonoGame": "크로스 플랫폼 게임 프레임워크",
    "Phaser": "HTML5 게임 프레임워크",
    "PixiJS": "2D WebGL 렌더러",
    "Babylon.js": "웹 3D 엔진",
    "PlayCanvas": "WebGL 게임 엔진",
    "Haxe": "크로스 플랫폼 툴킷",
    "Cocos2d-x": "크로스 플랫폼 게임 프레임워크",

    # Blockchain
    "Ethereum": "블록체인 플랫폼",
    "Blockchain ": "분산 원장 기술",

    # Embedded & IoT
    "Arduino": "오픈소스 전자 플랫폼",
    "Raspberry Pi": "소형 컴퓨터",
    "ARM Cortex-M": "ARM 마이크로컨트롤러 프로세서",
    "ARM Cortex-A": "ARM 애플리케이션 프로세서",
    "STM32": "STMicroelectronics 32비트 MCU",
    "AVR / PIC": "마이크로컨트롤러 아키텍처",
    "RISC-V": "오픈소스 ISA",
    "Nordic nRF": "무선 SoC",
    "FPGA": "프로그래밍 가능한 게이트 어레이",
    "FreeRTOS": "실시간 운영체제",
    "Zephyr": "RTOS 프로젝트",
    "Yocto Project": "임베디드 Linux 배포판 빌더",
    "Buildroot": "임베디드 Linux 빌드 시스템",
    "QNX / VxWorks": "실시간 운영체제",
    "uC/OS (Micrium)": "실시간 커널",
    "Bare-metal": "OS 없는 직접 하드웨어 프로그래밍",

    # Communication Protocols
    "UART": "범용 비동기 송수신기",
    "I2C": "직렬 통신 프로토콜",
    "SPI": "직렬 주변장치 인터페이스",
    "CAN bus": "차량 통신 프로토콜",
    "Modbus": "산업용 통신 프로토콜",
    "EtherCAT": "산업 이더넷 프로토콜",
    "BLE (Bluetooth Low Energy)": "저전력 블루투스",
    "Zigbee": "무선 메시 네트워크 표준",

    # Hardware & Low Level
    "HAL (Hardware Abstraction Layer)": "하드웨어 추상화 계층",
    "Device Driver": "하드웨어 제어 소프트웨어",
    "Register Level Programming": "레지스터 직접 제어 프로그래밍",
    "GPIO/PWM": "범용 입출력 / 펄스 폭 변조",
    "ADC/DAC": "아날로그-디지털 / 디지털-아날로그 변환기",
    "DMA(Direct Memory Access)": "직접 메모리 접근",
    "Watchdog Timer": "시스템 복구 타이머",
    "Verilog/VHDL": "하드웨어 기술 언어",

    # Embedded Development Tools
    "Keil MDK / IAR Workbench": "임베디드 개발 환경",
    "GNU Arm Toolchain (GCC)": "ARM용 GCC 툴체인",
    "OpenOCD": "온칩 디버거",
    "J-Link / ST-LINK": "디버그 프로브",
    "Oscilloscope / Logic Analyzer": "신호 분석 장비",
    "OTA (Over-The-Air)": "무선 펌웨어 업데이트",
    "Edge AI (TinyML)": "엣지 디바이스 머신러닝",
    "Bootloader": "부트로더",
    "MISRA C": "임베디드 C 코딩 표준",
    "Functional Safety (ISO 26262)": "자동차 기능 안전 표준",

    # Security Tools
    "Burp Suite": "웹 보안 테스팅 도구",
    "Metasploit": "침투 테스트 프레임워크",
    "ZAP (OWASP)": "웹 앱 보안 스캐너",
    "WAF (Web Application Firewall)": "웹 방화벽",
    "SQL Injection / XSS": "웹 취약점 공격 기법",
    "Wireshark": "네트워크 프로토콜 분석기",
    "Nmap": "네트워크 스캐너",
    "IDS/IPS": "침입 탐지/방지 시스템",
    "SSH / SFTP / FTP": "원격 접속 및 파일 전송 프로토콜",
    "WireGuard": "VPN 프로토콜",
    "Suricata": "네트워크 보안 모니터링",
    "Snort": "네트워크 침입 탐지 시스템",
    "OIDC": "OpenID Connect 인증 프로토콜",
    "MFA (Multi-Factor Authentication)": "다중 인증",
    "RBAC / ABAC": "역할/속성 기반 접근 제어",
    "Falco": "클라우드 네이티브 런타임 보안",
    "Trivy": "컨테이너 취약점 스캐너",
    "KMS (Key Management Service)": "암호화 키 관리 서비스",
    "Ghidra / IDA Pro": "리버스 엔지니어링 도구",
    "John the Ripper / Hashcat": "패스워드 크래킹 도구",
    "SIEM (Splunk, ELK Stack)": "보안 정보 및 이벤트 관리",
    "Snyk": "개발자 보안 플랫폼",
    "Coveralls": "코드 커버리지 서비스",
    "OpenVPN": "VPN 소프트웨어",

    # Other Services
    "Twilio": "클라우드 통신",
    "AdRoll": "리타게팅 플랫폼",
    "Acquia": "Drupal 클라우드",
    "Plesk": "웹 호스팅 플랫폼",
    "cPanel": "웹 호스팅 제어판",
    "Simple": "웹사이트 빌더",
    "Sitefinity": ".NET CMS",
    "Elementor": "WordPress 페이지 빌더",
    "Gravity Forms": "WordPress 폼 빌더",
    "WP Rocket ": "WordPress 캐싱 플러그인",
    "Laravel Forge": "Laravel 서버 관리",
    "Laravel Homestead": "Laravel 개발 환경",
    "Capistrano": "원격 서버 자동화",
    "Heroku Postgres": "Heroku PostgreSQL",
    "MongoLab": "MongoDB 호스팅",
    "Bootsnap": "Ruby/Rails 부팅 최적화",
    "Rails Spring": "Rails 애플리케이션 프리로더",
    "pre-commit": "Git 훅 프레임워크",
    "Hasura": "즉시 GraphQL API",
    "Supabase": "오픈소스 Firebase 대안",
    "Parse": "백엔드 서비스",
    "Redmine": "프로젝트 관리",
    "XenForo": "커뮤니티 포럼 소프트웨어",
    "vBulletin": "포럼 소프트웨어",
    "Discourse": "오픈소스 토론 플랫폼",
    "Blogger": "블로그 플랫폼",
    "Tumblr": "마이크로블로깅 플랫폼",
    "Medium": "온라인 퍼블리싱 플랫폼",
    "Buffer": "소셜 미디어 관리",
    "Dotenv": "환경변수 로더",
    "Yeoman": "웹 앱 스캐폴딩 도구",
    "Create React App": "React 앱 생성 도구",
    "Angular CLI": "Angular 명령줄 인터페이스",
    "Vue CLI": "Vue.js 개발 도구",
    "Quasar Framework": "Vue.js 기반 프레임워크",
    "Aurelia": "JavaScript 클라이언트 프레임워크",
    "Meteor": "풀스택 JavaScript 플랫폼",
    "Sails.js": "Node.js MVC 프레임워크",
    "LoopBack": "Node.js API 프레임워크",
    "Hapi": "Node.js 프레임워크",
    "Fastify": "빠른 웹 프레임워크",
    "Koa": "차세대 웹 프레임워크",
    "Express.js": "Node.js 웹 프레임워크",
    "Slim": "PHP 마이크로 프레임워크",
    "FatFree": "PHP 마이크로 프레임워크",
    "Zend Framework": "PHP 프레임워크",
    "Phalcon": "C 확장 PHP 프레임워크",
    "Yii": "PHP 프레임워크",
    "CodeIgniter": "PHP 프레임워크",
    "CakePHP": "PHP 프레임워크",
    "Symfony": "PHP 프레임워크",
    "Laravel": "PHP 웹 프레임워크",
    "Lumen": "Laravel 마이크로 프레임워크",
    "Odoo": "오픈소스 ERP",
    "Rundeck": "작업 스케줄러 및 자동화",
    "Talend": "데이터 통합 플랫폼",
    "Apache NiFi": "데이터 흐름 자동화",
    "Confluent": "Kafka 기반 스트리밍 플랫폼",
    "JHipster": "풀스택 개발 플랫폼",
    "React.js Boilerplate": "React 프로젝트 템플릿",
    "React Storybook": "UI 컴포넌트 개발 도구",
    "FullCalendar": "JavaScript 이벤트 캘린더",
    "Qt": "크로스 플랫폼 애플리케이션 프레임워크",
    "GTK": "GUI 툴킷",
    "GLSL": "OpenGL 셰이딩 언어",
    "OpenGL": "그래픽 API",
    "Vulkan": "그래픽 및 컴퓨팅 API",
    "DirectX": "Microsoft 멀티미디어 API",
    "FFMPEG": "멀티미디어 처리 프레임워크",
    "GStreamer": "멀티미디어 프레임워크",
    "ImageMagick": "이미지 처리 소프트웨어",
    "AWK": "텍스트 처리 언어",
    "GNU sed": "스트림 편집기",
    "Nix": "패키지 관리자",
    "Smalltalk": "객체지향 프로그래밍 언어",
    "PureBasic": "BASIC 프로그래밍 언어",
    "Visual Basic": "Microsoft 프로그래밍 언어",
    "Common Lisp": "Lisp 방언",
    "OCaml": "함수형 프로그래밍 언어",
    "Scheme": "Lisp 방언",
    "Racket": "Lisp 계열 언어",
    "Prolog": "논리 프로그래밍 언어",
    "Fortran": "과학 계산 언어",
    "COBOL": "비즈니스 프로그래밍 언어",
    "Pascal": "구조적 프로그래밍 언어",
    "Delphi": "Object Pascal IDE",
    "Ada": "고신뢰성 프로그래밍 언어",
    "VHDL": "하드웨어 기술 언어",
    "Verilog": "하드웨어 기술 언어",
    "SystemVerilog": "하드웨어 검증 언어",
    "Tcl": "스크립팅 언어",
    "Apex": "Salesforce 프로그래밍 언어",
    "ABAP": "SAP 프로그래밍 언어",
    "MATLAB": "수치 계산 언어",
    "Simulink": "모델 기반 설계 도구",
    "LabVIEW": "그래픽 프로그래밍 환경",
    "Scratch": "교육용 프로그래밍 언어",
    "ActionScript": "Flash 프로그래밍 언어",
    "ColdFusion": "웹 애플리케이션 개발 플랫폼",
    "Oracle PL/SQL": "Oracle 절차적 언어",
    "T-SQL": "SQL Server 확장 SQL",
    "MSSQL": "Microsoft SQL Server",
    "DB": "데이터베이스",
    "SQL": "구조화 쿼리 언어",
    "HTML5": "최신 HTML 표준",
    "CSS 3": "최신 CSS 표준",
    "ES6": "ECMAScript 2015",
    "JSON": "JavaScript Object Notation",
    "XML": "확장 마크업 언어",
    "YAML": "데이터 직렬화 언어",
    "TOML": "설정 파일 형식",
    "Markdown": "경량 마크업 언어",
    "reStructuredText": "마크업 언어",
    "AsciiDoc": "텍스트 문서 형식",
    "LaTeX": "문서 조판 시스템",
    "css-loader": "Webpack CSS 로더",
    "UglifyJS": "JavaScript 압축 도구",
    "ClojureScript": "Clojure의 JavaScript 컴파일 버전",
    "Dash": "API 문서 브라우저",
    "Stack Overflow": "개발자 Q&A 커뮤니티",
    "MEAN": "MongoDB, Express, Angular, Node.js 스택",
    "JAMstack": "JavaScript, API, Markup 아키텍처",
    "Serverless Framework": "서버리스 애플리케이션 프레임워크",
    "OpenFaaS": "서버리스 함수 프레임워크",
    "Apache Traffic Server": "캐싱 프록시 서버",
    "Vaadin": "Java 웹 앱 플랫폼",
    "GWT": "Google Web Toolkit",
    "Torch": "과학 컴퓨팅 프레임워크",
    "Sumo Logic": "로그 관리 및 분석",
    "Ktor": "Kotlin 비동기 프레임워크",
    "Chrome": "Google 웹 브라우저",
    "Google Chrome": "Google 웹 브라우저",
    "Firefox": "Mozilla 웹 브라우저",
    "Safari": "Apple 웹 브라우저",
    "Edge": "Microsoft 웹 브라우저",
    "Opera": "웹 브라우저",
    "PhantomJS": "헤드리스 WebKit",
    "Lighthouse": "웹 성능 측정 도구",
    "cURL": "URL 전송 도구",
    "wget": "파일 다운로드 도구",
    "rsync": "파일 동기화 도구",
    "Postman": "API 테스팅 도구",
    "Insomnia": "REST 클라이언트",
    "HTTPie": "HTTP 클라이언트",
}

# 기본 설명 템플릿으로 나머지 채우기
for tech in tech_list:
    if tech not in tech_descriptions:
        # 카테고리 추론 및 기본 설명 생성
        if any(keyword in tech.lower() for keyword in ['js', 'javascript', 'react', 'vue', 'angular', 'svelte']):
            tech_descriptions[tech] = f"{tech} JavaScript 라이브러리/프레임워크"
        elif 'python' in tech.lower() or tech in ['Django', 'Flask', 'FastAPI']:
            tech_descriptions[tech] = f"{tech} Python 라이브러리/프레임워크"
        elif any(keyword in tech.lower() for keyword in ['java', 'spring', 'hibernate']):
            tech_descriptions[tech] = f"{tech} Java 라이브러리/프레임워크"
        elif '.net' in tech.lower() or 'c#' in tech.lower():
            tech_descriptions[tech] = f"{tech} .NET/C# 도구"
        elif 'aws' in tech.lower() or 'amazon' in tech.lower():
            tech_descriptions[tech] = f"{tech} AWS 클라우드 서비스"
        elif 'azure' in tech.lower():
            tech_descriptions[tech] = f"{tech} Azure 클라우드 서비스"
        elif 'google' in tech.lower():
            tech_descriptions[tech] = f"{tech} Google 서비스/도구"
        elif 'database' in tech.lower() or 'db' in tech.lower() or tech in ['PostgreSQL', 'MySQL', 'MongoDB']:
            tech_descriptions[tech] = f"{tech} 데이터베이스 시스템"
        else:
            tech_descriptions[tech] = f"{tech} 개발 도구 및 기술"

# JSON 파일 생성
output_data = {
    "metadata": {
        "total_count": len(tech_list),
        "generated_date": "2025-01-20"
    },
    "technologies": tech_descriptions
}

with open('tech_descriptions.json', 'w', encoding='utf-8') as f:
    json.dump(output_data, f, ensure_ascii=False, indent=2)

print(f"✅ JSON 파일 생성 완료!")
print(f"총 {len(tech_descriptions)}개 기술에 대한 설명 작성됨")
print(f"파일 위치: tech_descriptions.json")
