# Generated by Django 5.0.1 on 2026-01-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0005_article_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='stack_count',
        ),
        migrations.AddField(
            model_name='techstack',
            name='article_stack_count',
            field=models.BigIntegerField(default=0, verbose_name='게시글 스택 언급량'),
        ),
    ]
