# Generated by Django 5.0.1 on 2026-01-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0009_merge_20260122_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='external_created_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='원본 게시글 생성일'),
        ),
    ]
