# Generated by Django 5.0.14 on 2026-01-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0011_add_article_mention_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='external_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='원본 게시글 생성일'),
        ),
    ]
