# Generated by Django 5.0.1 on 2026-01-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(verbose_name='사용자 답변')),
                ('ai_feedback', models.TextField(blank=True, null=True, verbose_name='AI 피드백')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='점수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
            ],
            options={
                'verbose_name': '면접 답변',
                'verbose_name_plural': '면접 답변 목록',
                'db_table': 'interview_answer',
            },
        ),
        migrations.CreateModel(
            name='InterviewPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='연습 일자')),
            ],
            options={
                'verbose_name': '면접 연습',
                'verbose_name_plural': '면접 연습 목록',
                'db_table': 'interview_practice',
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='질문')),
                ('answer_guide', models.TextField(blank=True, null=True, verbose_name='답변 가이드')),
                ('question_type', models.CharField(choices=[('tech', '기술 질문'), ('experience', '경험 질문'), ('behavioral', '행동 질문'), ('situational', '상황 질문')], default='tech', max_length=20, verbose_name='질문 유형')),
                ('difficulty', models.CharField(choices=[('easy', '쉬움'), ('medium', '보통'), ('hard', '어려움')], default='medium', max_length=10, verbose_name='난이도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일자')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
            ],
            options={
                'verbose_name': '면접 질문',
                'verbose_name_plural': '면접 질문 목록',
                'db_table': 'interview_question',
            },
        ),
    ]
